### ISSUE TITLE
特定のページでDBアクセスによって読み込みが遅くなる

### ISSUE THREAD

**Issue by gossan53** [maya40421/TOJWebapp#28]
submission数の増加により、学生全員などの情報を読み込むと異常におそくなる

**Comment by gossan53** [comment]
疑似DBを利用して実験した結果、肥大化しているテーブルに対してアクセスすると処理時間が膨れ上がれることがわかった。他のテーブルが肥大化している場合にはこの影響はない。
現在のSubmissionテーブルではコードを全て持っているのでこれをCodeテーブルなどに分ければ解決できそう。

**Comment by NKudryavka** [comment]
上手くINDEXを貼ればだいぶ早くなることがわかった（ホームの表示に500msくらい）
